repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: trailing-whitespace
        types: [markdown, yaml]

  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        language: system
        entry: pnpm biome check --write
        pass_filenames: false
        types_or: [javascript, json]
